branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode9.2
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=OSX
    - TEST_TYPE=CocoaPods
before_install:
- |
  if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = OSX ]; then
    bundle install
  fi
install:
- |
  if [ "$TEST_TYPE" = iOS ]; then
    ./TestSupport/setup_env.sh .env
  fi
script:
- |
  if [ "$TEST_TYPE" = iOS ]; then
    set -o pipefail
    xcodebuild -project SocketRocket.xcodeproj -scheme "SocketRocket-iOS" -sdk iphonesimulator build test
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint SocketRocket.podspec
    pod lib lint --use-libraries SocketRocket.podspec
  fi
